---
- name: Setting up Swarm
  # Similar to a Try/Except
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html#blocks-error-handling
  block:
    - name: Initiating the swarm with default parameters
      # https://docs.ansible.com/ansible/latest/modules/docker_swarm_module.html
      docker_swarm:
        state: present
      register: init_swarm

    - debug:
        var: init_swarm

    - name: "set fact: join token worker"
      set_fact:
        join_token_worker: "{{ init_swarm.swarm_facts.JoinTokens.Worker }}"

    - name: "set fact: join token manager"
      set_fact:
        join_token_manager: "{{ init_swarm.swarm_facts.JoinTokens.Manager }}"

  rescue:
    - name: Getting join manager token from existing Swarm
      # https://docs.ansible.com/ansible/latest/modules/command_module.html
      command: docker swarm join-token manager -q
      register: join_token_manager_command

    - name: Getting join worker token from existing Swarm
      # https://docs.ansible.com/ansible/latest/modules/command_module.html
      command: docker swarm join-token worker -q
      register: join_token_worker_command

    - name: "set fact: join_token_manager"
      set_fact:
        join_token_manager: "{{ join_token_manager_command['stdout'] }}"

    - name: "set fact: join_token_worker"
      set_fact:
        join_token_worker: "{{ join_token_worker_command['stdout'] }}"
